Added rapid-response xblock load test
mitodl/locust-tests pull request #5
Opened 2018-03-27 20:20 UTC by gsidebo

2018-03-27 20:39 UTC, gsidebo commented
@noisecapella @blarghmatey FYI. We should chat about how the data will be seeded to support this load test. Tobias and I chatted briefly and agreed that ideally we would have the data-seeding scripts located in this repo. I think course data seeding would ideally be done via an OLX representation of the courses, but that involves quite a few files per course so I decided on this JSON representation as a first draft.

I also want opinions on the general approach of the test. I wanted to avoid repeated logins and course enrollments (i.e.: if a user logged in or enrolled in any course in any locust instance, I wanted the login/enroll task to be a no-op).

2018-03-28 18:38 UTC, gsidebo commented
Addresses https://github.com/mitodl/rapid-response-xblock/issues/16

2018-03-29 18:04 UTC, blarghmatey commented
That seems sane and reasonable to me

2018-03-29 18:26 UTC, noisecapella requested changes
Just the one question, functionality works for me

2018-03-29 18:26 UTC, noisecapella commented on rapid_response/settings.py
> +# first try to load usernames from environment
What's the use case for supporting both? It seems like this data would be verbose enough where we would want to use files, I'm not sure what the use case is for environment variables

2018-03-29 18:43 UTC, gsidebo commented on rapid_response/settings.py
> +# first try to load usernames from environment
Copied over from the existing Micromasters test (https://github.com/mitodl/locust-tests/blob/master/micromasters/settings.py#L23). I figured it must have been relevant to running these load tests against a deployed instance

2018-04-02 14:30 UTC, noisecapella approved these changes

2018-04-02 16:19 UTC, merged